#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangTheThao.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CuaHangTheThao")]
	public partial class csdl_cuahangthethaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietDonHang(ChiTietDonHang instance);
    partial void UpdateChiTietDonHang(ChiTietDonHang instance);
    partial void DeleteChiTietDonHang(ChiTietDonHang instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertChiTietGioHang(ChiTietGioHang instance);
    partial void UpdateChiTietGioHang(ChiTietGioHang instance);
    partial void DeleteChiTietGioHang(ChiTietGioHang instance);
    partial void InsertDanhGiaSanPham(DanhGiaSanPham instance);
    partial void UpdateDanhGiaSanPham(DanhGiaSanPham instance);
    partial void DeleteDanhGiaSanPham(DanhGiaSanPham instance);
    partial void InsertDanhMucSanPham(DanhMucSanPham instance);
    partial void UpdateDanhMucSanPham(DanhMucSanPham instance);
    partial void DeleteDanhMucSanPham(DanhMucSanPham instance);
    partial void InsertDonHang(DonHang instance);
    partial void UpdateDonHang(DonHang instance);
    partial void DeleteDonHang(DonHang instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNhatKyHoatDong(NhatKyHoatDong instance);
    partial void UpdateNhatKyHoatDong(NhatKyHoatDong instance);
    partial void DeleteNhatKyHoatDong(NhatKyHoatDong instance);
    partial void InsertQuanTriVien(QuanTriVien instance);
    partial void UpdateQuanTriVien(QuanTriVien instance);
    partial void DeleteQuanTriVien(QuanTriVien instance);
    #endregion
		
		public csdl_cuahangthethaoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CuaHangTheThaoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public csdl_cuahangthethaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public csdl_cuahangthethaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public csdl_cuahangthethaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public csdl_cuahangthethaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this.GetTable<ChiTietDonHang>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietGioHang> ChiTietGioHangs
		{
			get
			{
				return this.GetTable<ChiTietGioHang>();
			}
		}
		
		public System.Data.Linq.Table<DanhGiaSanPham> DanhGiaSanPhams
		{
			get
			{
				return this.GetTable<DanhGiaSanPham>();
			}
		}
		
		public System.Data.Linq.Table<DanhMucSanPham> DanhMucSanPhams
		{
			get
			{
				return this.GetTable<DanhMucSanPham>();
			}
		}
		
		public System.Data.Linq.Table<DonHang> DonHangs
		{
			get
			{
				return this.GetTable<DonHang>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NhatKyHoatDong> NhatKyHoatDongs
		{
			get
			{
				return this.GetTable<NhatKyHoatDong>();
			}
		}
		
		public System.Data.Linq.Table<QuanTriVien> QuanTriViens
		{
			get
			{
				return this.GetTable<QuanTriVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonHang")]
	public partial class ChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _chi_tiet_don_hang_id;
		
		private string _don_hang_id;
		
		private string _san_pham_id;
		
		private int _so_luong;
		
		private decimal _gia;
		
		private EntityRef<SanPham> _SanPham;
		
		private EntityRef<DonHang> _DonHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchi_tiet_don_hang_idChanging(string value);
    partial void Onchi_tiet_don_hang_idChanged();
    partial void Ondon_hang_idChanging(string value);
    partial void Ondon_hang_idChanged();
    partial void Onsan_pham_idChanging(string value);
    partial void Onsan_pham_idChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void OngiaChanging(decimal value);
    partial void OngiaChanged();
    #endregion
		
		public ChiTietDonHang()
		{
			this._SanPham = default(EntityRef<SanPham>);
			this._DonHang = default(EntityRef<DonHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_don_hang_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string chi_tiet_don_hang_id
		{
			get
			{
				return this._chi_tiet_don_hang_id;
			}
			set
			{
				if ((this._chi_tiet_don_hang_id != value))
				{
					this.Onchi_tiet_don_hang_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_don_hang_id = value;
					this.SendPropertyChanged("chi_tiet_don_hang_id");
					this.Onchi_tiet_don_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_hang_id", DbType="VarChar(50)")]
		public string don_hang_id
		{
			get
			{
				return this._don_hang_id;
			}
			set
			{
				if ((this._don_hang_id != value))
				{
					if (this._DonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondon_hang_idChanging(value);
					this.SendPropertyChanging();
					this._don_hang_id = value;
					this.SendPropertyChanged("don_hang_id");
					this.Ondon_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="VarChar(50)")]
		public string san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2) NOT NULL")]
		public decimal gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietDonHang", Storage="_SanPham", ThisKey="san_pham_id", OtherKey="san_pham_id", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.ChiTietDonHangs.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonHangs.Add(this);
						this._san_pham_id = value.san_pham_id;
					}
					else
					{
						this._san_pham_id = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_DonHang", ThisKey="don_hang_id", OtherKey="don_hang_id", IsForeignKey=true)]
		public DonHang DonHang
		{
			get
			{
				return this._DonHang.Entity;
			}
			set
			{
				DonHang previousValue = this._DonHang.Entity;
				if (((previousValue != value) 
							|| (this._DonHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonHang.Entity = null;
						previousValue.ChiTietDonHangs.Remove(this);
					}
					this._DonHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonHangs.Add(this);
						this._don_hang_id = value.don_hang_id;
					}
					else
					{
						this._don_hang_id = default(string);
					}
					this.SendPropertyChanged("DonHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _san_pham_id;
		
		private string _ten;
		
		private string _mo_ta;
		
		private decimal _gia;
		
		private string _danh_muc_id;
		
		private int _so_luong_ton;
		
		private string _hinh_anh_url;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
		
		private EntitySet<ChiTietGioHang> _ChiTietGioHangs;
		
		private EntitySet<DanhGiaSanPham> _DanhGiaSanPhams;
		
		private EntityRef<DanhMucSanPham> _DanhMucSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsan_pham_idChanging(string value);
    partial void Onsan_pham_idChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void OngiaChanging(decimal value);
    partial void OngiaChanged();
    partial void Ondanh_muc_idChanging(string value);
    partial void Ondanh_muc_idChanged();
    partial void Onso_luong_tonChanging(int value);
    partial void Onso_luong_tonChanged();
    partial void Onhinh_anh_urlChanging(string value);
    partial void Onhinh_anh_urlChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public SanPham()
		{
			this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
			this._ChiTietGioHangs = new EntitySet<ChiTietGioHang>(new Action<ChiTietGioHang>(this.attach_ChiTietGioHangs), new Action<ChiTietGioHang>(this.detach_ChiTietGioHangs));
			this._DanhGiaSanPhams = new EntitySet<DanhGiaSanPham>(new Action<DanhGiaSanPham>(this.attach_DanhGiaSanPhams), new Action<DanhGiaSanPham>(this.detach_DanhGiaSanPhams));
			this._DanhMucSanPham = default(EntityRef<DanhMucSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(255)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2) NOT NULL")]
		public decimal gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danh_muc_id", DbType="VarChar(50)")]
		public string danh_muc_id
		{
			get
			{
				return this._danh_muc_id;
			}
			set
			{
				if ((this._danh_muc_id != value))
				{
					if (this._DanhMucSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondanh_muc_idChanging(value);
					this.SendPropertyChanging();
					this._danh_muc_id = value;
					this.SendPropertyChanged("danh_muc_id");
					this.Ondanh_muc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong_ton", DbType="Int NOT NULL")]
		public int so_luong_ton
		{
			get
			{
				return this._so_luong_ton;
			}
			set
			{
				if ((this._so_luong_ton != value))
				{
					this.Onso_luong_tonChanging(value);
					this.SendPropertyChanging();
					this._so_luong_ton = value;
					this.SendPropertyChanged("so_luong_ton");
					this.Onso_luong_tonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh_url", DbType="NVarChar(255)")]
		public string hinh_anh_url
		{
			get
			{
				return this._hinh_anh_url;
			}
			set
			{
				if ((this._hinh_anh_url != value))
				{
					this.Onhinh_anh_urlChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh_url = value;
					this.SendPropertyChanged("hinh_anh_url");
					this.Onhinh_anh_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="san_pham_id", OtherKey="san_pham_id")]
		public EntitySet<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this._ChiTietDonHangs;
			}
			set
			{
				this._ChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietGioHang", Storage="_ChiTietGioHangs", ThisKey="san_pham_id", OtherKey="san_pham_id")]
		public EntitySet<ChiTietGioHang> ChiTietGioHangs
		{
			get
			{
				return this._ChiTietGioHangs;
			}
			set
			{
				this._ChiTietGioHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_DanhGiaSanPham", Storage="_DanhGiaSanPhams", ThisKey="san_pham_id", OtherKey="san_pham_id")]
		public EntitySet<DanhGiaSanPham> DanhGiaSanPhams
		{
			get
			{
				return this._DanhGiaSanPhams;
			}
			set
			{
				this._DanhGiaSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMucSanPham_SanPham", Storage="_DanhMucSanPham", ThisKey="danh_muc_id", OtherKey="danh_muc_id", IsForeignKey=true)]
		public DanhMucSanPham DanhMucSanPham
		{
			get
			{
				return this._DanhMucSanPham.Entity;
			}
			set
			{
				DanhMucSanPham previousValue = this._DanhMucSanPham.Entity;
				if (((previousValue != value) 
							|| (this._DanhMucSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhMucSanPham.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._DanhMucSanPham.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._danh_muc_id = value.danh_muc_id;
					}
					else
					{
						this._danh_muc_id = default(string);
					}
					this.SendPropertyChanged("DanhMucSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
		
		private void attach_ChiTietGioHangs(ChiTietGioHang entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_ChiTietGioHangs(ChiTietGioHang entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
		
		private void attach_DanhGiaSanPhams(DanhGiaSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_DanhGiaSanPhams(DanhGiaSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietGioHang")]
	public partial class ChiTietGioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _chi_tiet_gio_hang_id;
		
		private string _gio_hang_id;
		
		private string _san_pham_id;
		
		private int _so_luong;
		
		private decimal _gia;
		
		private EntityRef<SanPham> _SanPham;
		
		private EntityRef<GioHang> _GioHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchi_tiet_gio_hang_idChanging(string value);
    partial void Onchi_tiet_gio_hang_idChanged();
    partial void Ongio_hang_idChanging(string value);
    partial void Ongio_hang_idChanged();
    partial void Onsan_pham_idChanging(string value);
    partial void Onsan_pham_idChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void OngiaChanging(decimal value);
    partial void OngiaChanged();
    #endregion
		
		public ChiTietGioHang()
		{
			this._SanPham = default(EntityRef<SanPham>);
			this._GioHang = default(EntityRef<GioHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_gio_hang_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string chi_tiet_gio_hang_id
		{
			get
			{
				return this._chi_tiet_gio_hang_id;
			}
			set
			{
				if ((this._chi_tiet_gio_hang_id != value))
				{
					this.Onchi_tiet_gio_hang_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_gio_hang_id = value;
					this.SendPropertyChanged("chi_tiet_gio_hang_id");
					this.Onchi_tiet_gio_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio_hang_id", DbType="VarChar(50)")]
		public string gio_hang_id
		{
			get
			{
				return this._gio_hang_id;
			}
			set
			{
				if ((this._gio_hang_id != value))
				{
					if (this._GioHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongio_hang_idChanging(value);
					this.SendPropertyChanging();
					this._gio_hang_id = value;
					this.SendPropertyChanged("gio_hang_id");
					this.Ongio_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="VarChar(50)")]
		public string san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2) NOT NULL")]
		public decimal gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietGioHang", Storage="_SanPham", ThisKey="san_pham_id", OtherKey="san_pham_id", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.ChiTietGioHangs.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.ChiTietGioHangs.Add(this);
						this._san_pham_id = value.san_pham_id;
					}
					else
					{
						this._san_pham_id = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GioHang_ChiTietGioHang", Storage="_GioHang", ThisKey="gio_hang_id", OtherKey="gio_hang_id", IsForeignKey=true)]
		public GioHang GioHang
		{
			get
			{
				return this._GioHang.Entity;
			}
			set
			{
				GioHang previousValue = this._GioHang.Entity;
				if (((previousValue != value) 
							|| (this._GioHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GioHang.Entity = null;
						previousValue.ChiTietGioHangs.Remove(this);
					}
					this._GioHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietGioHangs.Add(this);
						this._gio_hang_id = value.gio_hang_id;
					}
					else
					{
						this._gio_hang_id = default(string);
					}
					this.SendPropertyChanged("GioHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhGiaSanPham")]
	public partial class DanhGiaSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _danh_gia_id;
		
		private string _san_pham_id;
		
		private string _nguoi_dung_id;
		
		private int _danh_gia;
		
		private string _nhan_xet;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntityRef<SanPham> _SanPham;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondanh_gia_idChanging(string value);
    partial void Ondanh_gia_idChanged();
    partial void Onsan_pham_idChanging(string value);
    partial void Onsan_pham_idChanged();
    partial void Onnguoi_dung_idChanging(string value);
    partial void Onnguoi_dung_idChanged();
    partial void Ondanh_giaChanging(int value);
    partial void Ondanh_giaChanged();
    partial void Onnhan_xetChanging(string value);
    partial void Onnhan_xetChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public DanhGiaSanPham()
		{
			this._SanPham = default(EntityRef<SanPham>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danh_gia_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string danh_gia_id
		{
			get
			{
				return this._danh_gia_id;
			}
			set
			{
				if ((this._danh_gia_id != value))
				{
					this.Ondanh_gia_idChanging(value);
					this.SendPropertyChanging();
					this._danh_gia_id = value;
					this.SendPropertyChanged("danh_gia_id");
					this.Ondanh_gia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="VarChar(50)")]
		public string san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="VarChar(50)")]
		public string nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danh_gia", DbType="Int NOT NULL")]
		public int danh_gia
		{
			get
			{
				return this._danh_gia;
			}
			set
			{
				if ((this._danh_gia != value))
				{
					this.Ondanh_giaChanging(value);
					this.SendPropertyChanging();
					this._danh_gia = value;
					this.SendPropertyChanged("danh_gia");
					this.Ondanh_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhan_xet", DbType="NVarChar(255)")]
		public string nhan_xet
		{
			get
			{
				return this._nhan_xet;
			}
			set
			{
				if ((this._nhan_xet != value))
				{
					this.Onnhan_xetChanging(value);
					this.SendPropertyChanging();
					this._nhan_xet = value;
					this.SendPropertyChanged("nhan_xet");
					this.Onnhan_xetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_DanhGiaSanPham", Storage="_SanPham", ThisKey="san_pham_id", OtherKey="san_pham_id", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.DanhGiaSanPhams.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.DanhGiaSanPhams.Add(this);
						this._san_pham_id = value.san_pham_id;
					}
					else
					{
						this._san_pham_id = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DanhGiaSanPham", Storage="_NguoiDung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.DanhGiaSanPhams.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.DanhGiaSanPhams.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucSanPham")]
	public partial class DanhMucSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _danh_muc_id;
		
		private string _ten;
		
		private string _mo_ta;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondanh_muc_idChanging(string value);
    partial void Ondanh_muc_idChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    #endregion
		
		public DanhMucSanPham()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danh_muc_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string danh_muc_id
		{
			get
			{
				return this._danh_muc_id;
			}
			set
			{
				if ((this._danh_muc_id != value))
				{
					this.Ondanh_muc_idChanging(value);
					this.SendPropertyChanging();
					this._danh_muc_id = value;
					this.SendPropertyChanged("danh_muc_id");
					this.Ondanh_muc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(255)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMucSanPham_SanPham", Storage="_SanPhams", ThisKey="danh_muc_id", OtherKey="danh_muc_id")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.DanhMucSanPham = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.DanhMucSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonHang")]
	public partial class DonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _don_hang_id;
		
		private string _nguoi_dung_id;
		
		private System.Nullable<System.DateTime> _ngay_dat_hang;
		
		private string _trang_thai;
		
		private decimal _tong_tien;
		
		private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondon_hang_idChanging(string value);
    partial void Ondon_hang_idChanged();
    partial void Onnguoi_dung_idChanging(string value);
    partial void Onnguoi_dung_idChanged();
    partial void Onngay_dat_hangChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_dat_hangChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Ontong_tienChanging(decimal value);
    partial void Ontong_tienChanged();
    #endregion
		
		public DonHang()
		{
			this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_hang_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string don_hang_id
		{
			get
			{
				return this._don_hang_id;
			}
			set
			{
				if ((this._don_hang_id != value))
				{
					this.Ondon_hang_idChanging(value);
					this.SendPropertyChanging();
					this._don_hang_id = value;
					this.SendPropertyChanged("don_hang_id");
					this.Ondon_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="VarChar(50)")]
		public string nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dat_hang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_dat_hang
		{
			get
			{
				return this._ngay_dat_hang;
			}
			set
			{
				if ((this._ngay_dat_hang != value))
				{
					this.Onngay_dat_hangChanging(value);
					this.SendPropertyChanging();
					this._ngay_dat_hang = value;
					this.SendPropertyChanged("ngay_dat_hang");
					this.Onngay_dat_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Decimal(10,2) NOT NULL")]
		public decimal tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="don_hang_id", OtherKey="don_hang_id")]
		public EntitySet<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this._ChiTietDonHangs;
			}
			set
			{
				this._ChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DonHang", Storage="_NguoiDung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.DonHangs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.DonHangs.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.DonHang = this;
		}
		
		private void detach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.DonHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _gio_hang_id;
		
		private string _nguoi_dung_id;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<ChiTietGioHang> _ChiTietGioHangs;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongio_hang_idChanging(string value);
    partial void Ongio_hang_idChanged();
    partial void Onnguoi_dung_idChanging(string value);
    partial void Onnguoi_dung_idChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public GioHang()
		{
			this._ChiTietGioHangs = new EntitySet<ChiTietGioHang>(new Action<ChiTietGioHang>(this.attach_ChiTietGioHangs), new Action<ChiTietGioHang>(this.detach_ChiTietGioHangs));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio_hang_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string gio_hang_id
		{
			get
			{
				return this._gio_hang_id;
			}
			set
			{
				if ((this._gio_hang_id != value))
				{
					this.Ongio_hang_idChanging(value);
					this.SendPropertyChanging();
					this._gio_hang_id = value;
					this.SendPropertyChanged("gio_hang_id");
					this.Ongio_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="VarChar(50)")]
		public string nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GioHang_ChiTietGioHang", Storage="_ChiTietGioHangs", ThisKey="gio_hang_id", OtherKey="gio_hang_id")]
		public EntitySet<ChiTietGioHang> ChiTietGioHangs
		{
			get
			{
				return this._ChiTietGioHangs;
			}
			set
			{
				this._ChiTietGioHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_GioHang", Storage="_NguoiDung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.GioHangs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.GioHangs.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietGioHangs(ChiTietGioHang entity)
		{
			this.SendPropertyChanging();
			entity.GioHang = this;
		}
		
		private void detach_ChiTietGioHangs(ChiTietGioHang entity)
		{
			this.SendPropertyChanging();
			entity.GioHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nguoi_dung_id;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private string _email;
		
		private string _ten;
		
		private string _ho;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private System.Nullable<System.DateTime> _ngay_dang_ky;
		
		private EntitySet<DanhGiaSanPham> _DanhGiaSanPhams;
		
		private EntitySet<DonHang> _DonHangs;
		
		private EntitySet<GioHang> _GioHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnguoi_dung_idChanging(string value);
    partial void Onnguoi_dung_idChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnhoChanging(string value);
    partial void OnhoChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onngay_dang_kyChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_dang_kyChanged();
    #endregion
		
		public NguoiDung()
		{
			this._DanhGiaSanPhams = new EntitySet<DanhGiaSanPham>(new Action<DanhGiaSanPham>(this.attach_DanhGiaSanPhams), new Action<DanhGiaSanPham>(this.detach_DanhGiaSanPhams));
			this._DonHangs = new EntitySet<DonHang>(new Action<DonHang>(this.attach_DonHangs), new Action<DonHang>(this.detach_DonHangs));
			this._GioHangs = new EntitySet<GioHang>(new Action<GioHang>(this.attach_GioHangs), new Action<GioHang>(this.detach_GioHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho", DbType="NVarChar(50)")]
		public string ho
		{
			get
			{
				return this._ho;
			}
			set
			{
				if ((this._ho != value))
				{
					this.OnhoChanging(value);
					this.SendPropertyChanging();
					this._ho = value;
					this.SendPropertyChanged("ho");
					this.OnhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="NVarChar(15)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dang_ky", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_dang_ky
		{
			get
			{
				return this._ngay_dang_ky;
			}
			set
			{
				if ((this._ngay_dang_ky != value))
				{
					this.Onngay_dang_kyChanging(value);
					this.SendPropertyChanging();
					this._ngay_dang_ky = value;
					this.SendPropertyChanged("ngay_dang_ky");
					this.Onngay_dang_kyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DanhGiaSanPham", Storage="_DanhGiaSanPhams", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<DanhGiaSanPham> DanhGiaSanPhams
		{
			get
			{
				return this._DanhGiaSanPhams;
			}
			set
			{
				this._DanhGiaSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DonHang", Storage="_DonHangs", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<DonHang> DonHangs
		{
			get
			{
				return this._DonHangs;
			}
			set
			{
				this._DonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_GioHang", Storage="_GioHangs", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<GioHang> GioHangs
		{
			get
			{
				return this._GioHangs;
			}
			set
			{
				this._GioHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhGiaSanPhams(DanhGiaSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_DanhGiaSanPhams(DanhGiaSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhatKyHoatDong")]
	public partial class NhatKyHoatDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nhat_ky_id;
		
		private string _quan_tri_vien_id;
		
		private string _hanh_dong;
		
		private System.Nullable<System.DateTime> _thoi_gian;
		
		private EntityRef<QuanTriVien> _QuanTriVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnhat_ky_idChanging(string value);
    partial void Onnhat_ky_idChanged();
    partial void Onquan_tri_vien_idChanging(string value);
    partial void Onquan_tri_vien_idChanged();
    partial void Onhanh_dongChanging(string value);
    partial void Onhanh_dongChanged();
    partial void Onthoi_gianChanging(System.Nullable<System.DateTime> value);
    partial void Onthoi_gianChanged();
    #endregion
		
		public NhatKyHoatDong()
		{
			this._QuanTriVien = default(EntityRef<QuanTriVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhat_ky_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nhat_ky_id
		{
			get
			{
				return this._nhat_ky_id;
			}
			set
			{
				if ((this._nhat_ky_id != value))
				{
					this.Onnhat_ky_idChanging(value);
					this.SendPropertyChanging();
					this._nhat_ky_id = value;
					this.SendPropertyChanged("nhat_ky_id");
					this.Onnhat_ky_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quan_tri_vien_id", DbType="VarChar(50)")]
		public string quan_tri_vien_id
		{
			get
			{
				return this._quan_tri_vien_id;
			}
			set
			{
				if ((this._quan_tri_vien_id != value))
				{
					if (this._QuanTriVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onquan_tri_vien_idChanging(value);
					this.SendPropertyChanging();
					this._quan_tri_vien_id = value;
					this.SendPropertyChanged("quan_tri_vien_id");
					this.Onquan_tri_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanh_dong", DbType="NVarChar(255)")]
		public string hanh_dong
		{
			get
			{
				return this._hanh_dong;
			}
			set
			{
				if ((this._hanh_dong != value))
				{
					this.Onhanh_dongChanging(value);
					this.SendPropertyChanging();
					this._hanh_dong = value;
					this.SendPropertyChanged("hanh_dong");
					this.Onhanh_dongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoi_gian", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoi_gian
		{
			get
			{
				return this._thoi_gian;
			}
			set
			{
				if ((this._thoi_gian != value))
				{
					this.Onthoi_gianChanging(value);
					this.SendPropertyChanging();
					this._thoi_gian = value;
					this.SendPropertyChanged("thoi_gian");
					this.Onthoi_gianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanTriVien_NhatKyHoatDong", Storage="_QuanTriVien", ThisKey="quan_tri_vien_id", OtherKey="quan_tri_vien_id", IsForeignKey=true)]
		public QuanTriVien QuanTriVien
		{
			get
			{
				return this._QuanTriVien.Entity;
			}
			set
			{
				QuanTriVien previousValue = this._QuanTriVien.Entity;
				if (((previousValue != value) 
							|| (this._QuanTriVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanTriVien.Entity = null;
						previousValue.NhatKyHoatDongs.Remove(this);
					}
					this._QuanTriVien.Entity = value;
					if ((value != null))
					{
						value.NhatKyHoatDongs.Add(this);
						this._quan_tri_vien_id = value.quan_tri_vien_id;
					}
					else
					{
						this._quan_tri_vien_id = default(string);
					}
					this.SendPropertyChanged("QuanTriVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanTriVien")]
	public partial class QuanTriVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _quan_tri_vien_id;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private string _email;
		
		private string _vai_tro;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<NhatKyHoatDong> _NhatKyHoatDongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onquan_tri_vien_idChanging(string value);
    partial void Onquan_tri_vien_idChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onvai_troChanging(string value);
    partial void Onvai_troChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public QuanTriVien()
		{
			this._NhatKyHoatDongs = new EntitySet<NhatKyHoatDong>(new Action<NhatKyHoatDong>(this.attach_NhatKyHoatDongs), new Action<NhatKyHoatDong>(this.detach_NhatKyHoatDongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quan_tri_vien_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string quan_tri_vien_id
		{
			get
			{
				return this._quan_tri_vien_id;
			}
			set
			{
				if ((this._quan_tri_vien_id != value))
				{
					this.Onquan_tri_vien_idChanging(value);
					this.SendPropertyChanging();
					this._quan_tri_vien_id = value;
					this.SendPropertyChanged("quan_tri_vien_id");
					this.Onquan_tri_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro", DbType="NVarChar(50)")]
		public string vai_tro
		{
			get
			{
				return this._vai_tro;
			}
			set
			{
				if ((this._vai_tro != value))
				{
					this.Onvai_troChanging(value);
					this.SendPropertyChanging();
					this._vai_tro = value;
					this.SendPropertyChanged("vai_tro");
					this.Onvai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanTriVien_NhatKyHoatDong", Storage="_NhatKyHoatDongs", ThisKey="quan_tri_vien_id", OtherKey="quan_tri_vien_id")]
		public EntitySet<NhatKyHoatDong> NhatKyHoatDongs
		{
			get
			{
				return this._NhatKyHoatDongs;
			}
			set
			{
				this._NhatKyHoatDongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhatKyHoatDongs(NhatKyHoatDong entity)
		{
			this.SendPropertyChanging();
			entity.QuanTriVien = this;
		}
		
		private void detach_NhatKyHoatDongs(NhatKyHoatDong entity)
		{
			this.SendPropertyChanging();
			entity.QuanTriVien = null;
		}
	}
}
#pragma warning restore 1591
